---
- name: Update Apache to the latest version on Raspberry Pi
  hosts: 192.168.2.53
  become: true
  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade apache2 to latest version
      apt:
        name: apache2
        state: latest

    - name: Ensure Apache service is running
      service:
        name: apache2
        state: started
        enabled: yes
